### ISSUE TITLE
style(LayerSwitcher): couleur slider opacité

### ISSUE THREAD

**Issue by elias75015** [IGNF/geoportal-extensions-openlayers#123]
Changer la couleur du slider d'opacité :

![image](https://github.com/user-attachments/assets/29493595-2a0e-4ad4-be8a-0ec529a15645)

par 

![image](https://github.com/user-attachments/assets/2b83a63e-1bd1-44d2-b6b5-ced372c9fb98)

**Comment by elias75015** [comment]
Je ne comprends pas trop :

Notre code : 
![image](https://github.com/user-attachments/assets/82ef822d-3133-4ac0-8eb2-e439370dd19e)

Le code du slider DSFR (https://www.systeme-de-design.gouv.fr/composants-et-modeles/composants/curseur-range) : 
![image](https://github.com/user-attachments/assets/ff96a55d-282f-49d6-9dfa-6dccbfaa06f8)


Mais le rendu ne colle pas (d'ailleurs on s'en apercoit en switchant de theme light/dark).

Sous Chrome : 
![image](https://github.com/user-attachments/assets/0f1fb94b-b0f3-4d86-82d3-9aad6cb5917b)

Sous FF : 
![image](https://github.com/user-attachments/assets/8b51aaee-f3bd-441b-85df-76bfb5ac6878)

**Comment by lowzonenose** [comment]
https://nosmoking.developpez.com/demos/css/range-slider-custom.html

**Comment by azarz** [comment]
Il fallait ajouter un peu de js :
En inspectant les sliders sur la page du DSFR :
div class="fr-range" data-fr-js-range="true" **style="--progress-right: 12.00px;"**

Et ajouter l'attribut data-fr-js-range="true" au range slider.
cf https://github.com/IGNF/geoportal-extensions-openlayers/pull/130
